const data = [
    "1. a) B (goes - HTĐ với Lan); b) D (gets up - thói quen); c) C (am riding - 'Right now')",
    "2. a) A (rises - sự thật hiển nhiên); b) A (lessons); c) A (Literature - môn học)",
    "3. a) B (wake up/brush/go - HTĐ); b) A (go/am going - thói quen/tạm thời)",
    "4. a) A (begins - lịch trình cố định); b) A (is increasing - sự thay đổi đang diễn ra)",
    "5. a) A (started/answered/spoke - hành động liên tiếp quá khứ); b) A (Were they walking?)",
    "6. a) D (how); b) A (what); c) A",
    "7. a) C (Shoulders); b) C (fingers); c) A (hard-working)",
    "8. a) B (art gallery); b) D (railway station); c) C (has worked - HTHT với for 15 years)",
    "9. a) B (have been - HTHT với since); b) A (finished / has been)",
    "10. a) A (affects - tác động); b) D (beautifully - trạng từ bổ nghĩa cho động từ)",
    "11. a) B (keep fit - giữ dáng); b) B (a place / the night)",
    "12. a) C (more / less - ăn nhiều rau hơn/ít đồ ăn nhanh); b) D (sickness - danh từ)",
    "13. a) C (repeating - mind + V-ing); b) D (wearing - fancy + V-ing)",
    "14. a) C (so... that - quá đến nỗi mà); b) B (Despite + cụm danh từ)",
    "15. a) C (so... that); b) B (However - Tuy nhiên)",
    "16. a) A (should go - giả định với suggest); b) B (which - ĐTQH cho vật)",
    "17. A (wants - Câu điều kiện loại 1)",
    "18. A (might - khả năng xảy ra)",
    "19. a) A (were - Câu ước hiện tại); b) A (look after - chăm sóc)",
    "20. a) A (rubbish); b) A (environment)",
    "21. a) C (planet); b) B (riding a horse); c) C (making models)",
    "22. A (collect stamps)",
    "23. a) A (skin condition); b) A (should spend)",
    "24. a) C (whose - sở hữu); b) C (who - thay cho người)",
    "25. A (doesn't / should do - Câu điều kiện loại 1)",
    "26. a) A (The harder / the better - So sánh kép); b) A (sculpture)",
    "27. a) C (the cheapest one); b) A (traditional)",
    "28. a) C (pot - âm /ɒ/); b) A (can - âm /æ/)",
    "29. a) D (dangerously); b) A (fantasy)",
    "30. a) A (comedy); b) B (violent)",
    "31. a) B (must-see); b) B (shocking)",
    "32. a) A (folk dance); b) C (celebration)",
    "33. a) B (run out - cạn kiệt); b) B (renewable - tái tạo)",
    "34. a) C (working/studying - hành động song song QK); b) D (did/break - câu hỏi QKĐ)",
    "35. a) A (electricity); b) C (nuclear)",
    "36. a) A (Where does Susie work?); b) C (going / watching)",
    "37. A (started / answered / spoke)",
    "38. a) A (was sitting / was looking - hành động song song); b) A (Were they walking?)",
    "39. a) B (haven't decided); b) C (have read); c) B (zebra crossing)",
    "40. a) C (Will / take - tương lai đơn); b) A (how)",
    "41. A (more stressful than - so sánh hơn tính từ dài)",
    "42. a) A (wrote - câu ước hiện tại); b) B (to have / must)",
    "43. a) A (midterm test); b) B (handlebars)",
    "44. a) D (School ahead); b) C (wizard)",
    "45. a) A (Moving film - phim cảm động); b) D (horror film); c) A (on the wall)",
    "46. a) A (tính từ sở hữu + N); b) A (can - khả năng hiện tại)",
    "47. a) observe; b) preservation",
    "48. a) A; b) A (much - danh từ không đếm được)",
    "49. a) C (đồng ý lời mời); b) C (a lot of)",
    "50. a) A (lùi thì, must -> had to); b) A (QKĐ / HTĐ)",
    "51. A (Câu điều kiện loại 1)",
    "52. a) A; b) C",
    "53. a) C (suggest + V-ing); b) A",
    "54. a) D (advise + V-ing không tân ngữ); b) D (Would you mind if I + V2/ed)",
    "55. a) B (Tuy nhiên); b) D (harder / more patiently - so sánh hơn trạng từ)",
    "56. a) D (experience - không đếm được); b) C (Its - của nó)",
    "57. a) D (trường nội trú); b) B (nhà sàn)",
    "58. a) D (tủ lạnh); b) A (bàn tay); c) A (thông minh)",
    "59. a) A (quảng trường); b) D (đền/chùa); c) C (sạt lở đất)",
    "60. a) C (động đất); b) A (bộ đồ cứu hộ)",
    "61. a) B (nhà rông); b) A (sáo trúc)",
    "62. a) B (gia súc); b) A (đặc điểm độc đáo)",
    "63. a) B (đóng vai trò); b) D (cây nêu)",
    "64. a) B (thân thiện môi trường); b) A (chức năng)",
    "65. a) B (khí thải); b) B (chế độ lái tự động)",
    "66. a) C (chạy bằng); b) B (sự phát minh); c) C (be crazy about)",
    "67. a) B (giữ liên lạc); b) B (Are you eating?)",
    "68. a) C (hành động đang xảy ra); b) A",
    "69. a) A (keen on + V-ing); b) A (QKĐ)",
    "70. a) A (quá khứ của be); b) B (lịch phát sóng)",
    "71. B (went / had)",
    "72. a) C (popular for); b) A (tương lai đơn)",
    "73. a) D (phủ định QKĐ); b) A (không nên làm vỡ đồ); c) B (kênh truyền hình)",
    "74. a) A (HTHT); b) A (so sánh kép)",
    "75. a) A (quyết định lúc nói); b) D (tổ chức Tết)",
    "76. a) what; b) how",
    "77. a) where; b) who",
    "78. a) C (educational programme); b) A (vợt)",
    "79. a) A (kính bảo hộ); b) B (yêu thể thao)",
    "80. a) D (cuộc thi); b) C (thức ăn đường phố)",
    "81. a) C (chợ nổi); b) D (UFO)",
    "82. a) C (quá khứ teach); b) D (tủ quần áo)",
    "83. a) C (đang dựng lều thì gió mạnh); b) C (triển lãm)",
    "84. a) B (have had - HTHT); b) D; c) D (sa mạc)",
    "85. a) B (won't be - TLĐ); b) A (thung lũng)",
    "86. a) D; b) A (băng cá nhân)",
    "87. a) A (ước hiện tại); b) C (vứt rác); c) A (dãy núi)",
    "88. A (câu ước ở hiện tại)",
    "89. a) A (bắt buộc); b) C (kỷ niệm)",
    "90. a) B (chương trình giáo dục); b) B",
    "91. a) B (ĐTQH vật); b) B (mái nhà)",
    "92. a) D (prevent from + V-ing); b) B (trao đổi)",
    "93. a) C (faster - so sánh hơn trạng từ); b) C (chia thành)",
    "94. a) C (tháng dùng in); b) C; c) B",
    "95. a) A (hầu như không); b) D (x - have breakfast)",
    "96. a) D (vật duy nhất); b) B (mụn); c) B (ăn nhiều rau)",
    "97. a) A (suốt kỳ nghỉ); b) A (người ăn chay)",
    "98. a) A/C (gây quỹ); b) A (trước khi)",
    "99. a) A (make + O + V-bare); b) B (góp mặt)",
    "100. a) D (hoạt động cộng đồng); b) B (gà tây)",
    "101. a) A (người vô gia cư); b) B (nhạc cụ)",
    "102. a) D (người già); b) D (chán)",
    "103. a) B (works of art); b) A (phim Cannes)",
    "104. B (biểu tượng)",
    "105. a) A (than đá); b) B (năng lượng mặt trời)",
    "106. a) B (tính từ); b) A (thiết bị bay); c) B (pin mặt trời)",
    "107. a) B (xe một bánh); b) A (độc nhất)",
    "108. a) D (đường bờ biển); b) C (fancy + V-ing); c) A (giải trí)",
    "109. a) A (cày cấy - Plough v); b) C (bộ đồ thủ công)",
    "110. a) A (gia súc); b) A (dỡ hàng)",
    "111. a) A (hái quả); b) B (được đào tạo tốt)",
    "112. C (communication skills - kỹ năng giao tiếp)",
    "113. B (tập trung vào)",
    "114. a) A (giữ bình tĩnh); b) A (nhóm dân tộc)",
    "115. a) B (miền núi); b) A (lễ khai trương)",
    "116. a) C (chúc thọ); b) D (thờ cúng)",
    "117. a) A (phép tắc ăn uống); b) C (truyền thống)",
    "118. a) B (đoàn tụ); b) A (trải nghiệm)",
    "119. C (nhà băng Inuit)",
    "120. A (lối sống du mục)",
    "121. A (giảm thiểu)",
    "122. a) C (dấu chân carbon); b) B (núi lửa)",
    "123. B (thiệt hại)",
    "124. a) A (vòi rồng); b) A (nạn nhân)",
    "125. a) D (nhấn âm 2); b) B (nhấn âm 2)",
    "126. a) C (hội nghị truyền hình); b) C (kết nối mạng)",
    "127. B (điểm danh)",
    "128. D (hố thiên thạch)",
    "129. a) A (giả định); b) D (la bàn)",
    "130. a) A (sum họp); b) A (phim hài)",
    "131. B (suggest + S + V-bare)",
    "132. D (should buy)",
    "133. a) B (HTĐ số ít is); b) A (earache)",
    "134. a) B (HTĐ số ít is); b) A (earache)",
    "135. a) D (ước hiện tại could go); b) A",
    "136. A (Câu điều kiện loại 1)",
    "137. a) A (can); b) C (Hyperloop)",
    "138. D (at the moment)",
    "139. a) B (at the weekend); b) D (detest = ghét)",
    "140. 1) False; 2) True",
    "141. 1) True; 2) True",
    "142. a) C (shouldn't); b) A (harvest crops)",
    "143. a) A (some + N không đếm được); b) C (expectation)",
    "144. a) B (water không đếm được); b) B (thả cá chép release)",
    "145. A (mushers - lái chó kéo xe)",
    "146. B",
    "147. a) A (habitat); b) A (không mặc cả)",
    "148. a) B (convenience store); b) B (home-grown)",
    "149. a) B (shopaholic); b) A (wireless access)",
    "150. A (property - tài sản)",
    "151. B (social networks)",
    "152. D (win scholarships)",
    "153. a) C (contact lens); b) D (scanner)",
    "154. A (Zoom platform)",
    "155. a) C (experiments on animals); b) B (possibility)",
    "156. C (rocket)",
    "157. a) A (get on with); b) A (remind of)",
    "158. a) A (electrician); b) D (police officer); c) C (garbage collector)",
    "159. a) C (artisans); b) A (craft village)",
    "160. a) B (passed down - truyền lại); b) B (come back - quay về)"
];

const keysContainer = document.getElementById('quick-keys-list');
const detailsContainer = document.getElementById('answer-details');

data.forEach((item) => {
    const dotIndex = item.indexOf('.');
    const qNum = item.substring(0, dotIndex).trim();
    const content = item.substring(dotIndex + 1).trim();
    const keyBtn = document.createElement('div');
    keyBtn.className = 'key-item';
    keyBtn.innerText = qNum;
    keyBtn.onclick = () => scrollToDetail(`q${qNum}`);
    keysContainer.appendChild(keyBtn);
    const card = document.createElement('div');
    card.className = 'detail-card';
    card.id = `q${qNum}`;
    card.innerHTML = `
        <h2>Question ${qNum}</h2>
        <div class="ans-content">${content.replace(/;/g, '<br>')}</div>
    `;
    detailsContainer.appendChild(card);
});

function scrollToDetail(id) {
    const element = document.getElementById(id);
    if (element) {
        element.scrollIntoView({ behavior: 'smooth', block: 'start' });
        
        document.querySelectorAll('.detail-card').forEach(c => c.style.borderLeft = "none");
        element.style.borderLeft = "5px solid #5498ba";
        element.style.backgroundColor = "#f9feff";
    }
}